apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0ca5819c749353da6" # As per terraform output for public subnet
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerSourceRanges: []
